INTERFACE_POOLS:
  OV:
    INTERFACE_POOL:
    # 反代节点
      - url: https://api.live.bilibili.com
        # 权重
        weight: 1
        # (可选)最大重试次数，默认为2次
        max_retries: 2
        # (可选) 重试间隔时间（秒），默认为10秒
        retry_interval: 10
  CN:
    INTERFACE_POOL:
      - url: https://api.live.bilibili.com
        weight: 1

COOKIESTR_POOL:
  - DedeUserID=121323;DedeUserID__ckMd5=124;Expires=123;SESSDATA=123123123;bili_jct=1234124;LIVE_BUVID=1241353
  - DedeUserID=121321233;DedeUserID__ckMd5=1244;Exp123ires=123123;SESSDATA=123123123;bili_jct=123412124;LIVE_BUVID=1241135
  - DedeUserID=d1;DedeUserID__ckMd5=13f32;Exp123ires=12d;SESSDATA=asr2;bili_jct=123412124;LIVE_BUVID=123