# (可选)全局节点健康检查间隔(秒)，默认180秒
INTERFACE_HEALTH_CHECK_INTERVAL: 180

# (可选)Cookie健康检查间隔(秒)，默认3600秒
COOKIE_HEALTH_CHECK_INTERVAL: 3600

# (可选)全局节点最大重试次数，默认2次
DEFAULT_MAX_RETRIES: 2

# (可选)全局节点重试间隔时间(秒)，默认10秒
DEFAULT_RETRY_INTERVAL: 10

# 代理池
INTERFACE_POOLS:
  # 代理池名称
  OV:
    INTERFACE_POOL:
      # 节点URL/IP端口
      - url: http(s)://example.com
        # 权重
        weight: 1
        # (可选)最大重试次数，默认2次
        max_retries: 2
        # (可选)重试间隔时间(秒)，默认10秒
        retry_interval: 10
      - url: http://114.51.41.91:9810
        weight: 1
  CN:
    INTERFACE_POOL:
      - url: https://api.live.bilibili.com
        weight: 1

# COOKIE池
COOKIESTR_POOL:
  # COOKIE名称/ID
  USER1:
    - cookie: DedeUserID=114514;DedeUserID__ckMd5=114514;Expires=114514;SESSDATA=114514;bili_jct=114514;LIVE_BUVID=114514
      weight: 1
  USER2:
    - cookie: DedeUserID=1919810;DedeUserID__ckMd5=1919810;Exp123ires=1919810;SESSDATA=1919810;bili_jct=1919810;LIVE_BUVID=1919810
      weight: 2