# (可选)监听IP，默认127.0.0.1
HOST: 127.0.0.1
# (可选)监听端口，默认5687
PORT: 5687

# (必要)API调用密匙，空着会报错
API_KEY: "1145141919810"

# API状态页面
API_STATUS:
  # (可选)是否启用状态页面，默认否
  enable: false
  # (可选)认证账号，默认admin
  username: "admin"
  # (可选)认证密码，默认admin
  password: "admin"

# 健康检查
HEALTH_CHECK:
  # API配置
  API:
    # (可选)全局 API健康检查 间隔(秒)，默认180秒
    INTERVAL: 180
    # (可选)全局 API健康检查 错误 最大重试次数，默认2次
    MAX_RETRY: 2
    # (可选)全局 API健康检查 错误 重试间隔时间(秒)，默认10秒
    MAX_RETRY_INTERVAL: 10
  COOKIE:
    # (可选)全局 Cookie健康检查间隔(秒)，默认3600秒
    INTERVAL: 3600

# API池
INTERFACE_POOLS:
  # API池名称
  OV:
    INTERFACE_POOL:
      # API URL/IP端口
      - url: http(s)://example.com
        # 权重
        weight: 1
        # (可选)最大重试次数，默认2次
        max_retries: 2
        # (可选)重试间隔时间(秒)，默认10秒
        retry_interval: 10
      - url: http://114.51.41.91:9810
        weight: 1
  CN:
    INTERFACE_POOL:
      - url: https://api.live.bilibili.com
        weight: 1

# COOKIE池
COOKIESTR_POOL:
  # COOKIE名称/ID
  USER1:
    - cookie: DedeUserID=114514;DedeUserID__ckMd5=114514;Expires=114514;SESSDATA=114514;bili_jct=114514;LIVE_BUVID=114514
      weight: 1

# SMTP邮件通知
SMTP:
  # (可选)是否启用SMTP，默认否
  enable: false
  # (必要)发件人邮箱
  sender_email: "your_email@example.com"
  # (必要)发件人邮箱密码
  sender_password: "your_email_password"
  # (必要)收件人邮箱
  receiver_email: "receiver_email@example.com"
  # (必要)发件人邮箱的SMTP服务器地址
  smtp_server: "smtp.exmail.com"
  # (必要)是否使用SSL加密连接SMTP服务器
  smtp_ssl: True
  # (必要)SMTP端口
  smtp_port: 465
