# (可选)节点健康检查间隔(秒)，默认180秒
INTERFACE_HEALTH_CHECK_INTERVAL: 180

INTERFACE_POOLS:
  OV:
    INTERFACE_POOL:
      # 节点
      - url: http(s)://example.com
        # 权重
        weight: 1
        # (可选)最大重试次数，默认2次
        max_retries: 2
        # (可选)重试间隔时间(秒)，默认10秒
        retry_interval: 10
      - url: http://114.51.41.91:9810
        weight: 1
  CN:
    INTERFACE_POOL:
      - url: https://api.live.bilibili.com
        weight: 1

COOKIESTR_POOL:
  - DedeUserID=114514;DedeUserID__ckMd5=114514;Expires=114514;SESSDATA=114514;bili_jct=114514;LIVE_BUVID=114514
  - DedeUserID=1919810;DedeUserID__ckMd5=1919810;Exp123ires=1919810;SESSDATA=1919810;bili_jct=1919810;LIVE_BUVID=1919810